set nocompatible

if filereadable(expand("~/.vim/plugins.vim"))
  source ~/.vim/plugins.vim
endif

let mapleader=","

if filereadable(expand("~/.vim/remaps.vim"))
  source ~/.vim/remaps.vim
endif

if filereadable(expand("~/.vim/autocmds.vim"))
  source ~/.vim/autocmds.vim
endif

set laststatus=2

set showcmd

set foldmethod=syntax
set foldlevel=99

set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=4
set expandtab

set number
set relativenumber

set autoread
set visualbell

set noswapfile
set nobackup
set nowritebackup

set backspace=2

if has('persistent_undo')
  silent! call mkdir(expand("~/.vim/backups"), "p")
  set undodir=~/.vim/backups
  set undofile
end

set list listchars=tab:»·,trail:·
set iskeyword+=-

set nowrap
set linebreak

set scrolloff=8

set clipboard=unnamed
set mouse=a

set t_Co=256
set background=dark
colorscheme base16-tomorrow

highlight SpecialKey ctermfg=237

nnoremap <Leader>o :CtrlPCurWD<CR>
nnoremap <Leader>O :CtrlP<CR>
let g:ctrlp_max_files = 0
let g:ctrlp_show_hidden = 1
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
let g:ctrlp_use_caching = 0

set colorcolumn=80

set gdefault
set ignorecase

" Open new splits panes to below and to the right
set splitbelow
set splitright

" Configure vim-airline
let g:airline_powerline_fonts = 1

" HTML tags
let g:html_indent_inctags = "main"

" Vim SLIME
let g:slime_target = "tmux"

" Syntastic
let g:syntastic_javascript_checkers = ['eslint']
if executable(system('echo -n `npm bin`') . '/eslint')
  let g:syntastic_javascript_eslint_exec = '`npm bin`/eslint'
else
  let g:syntastic_javascript_eslint_exec = '`which eslint`'
endif
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1

" NERDTree
map <C-n> :NERDTreeToggle<CR>

let g:go_fmt_command = "goimports"
let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
