export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/local/sbin:$PATH"
export PATH="$GOPATH/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="`yarn global bin`:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman/:/usr/local/opt/findutils/share/man/:$MANPATH"

fpath+=~/.zfunc

# Don't bother display the execution time
PURE_CMD_MAX_EXEC_TIME=999999
PURE_PROMPT_SYMBOL=$

source $ZSH/antigen/antigen.zsh

antigen bundle felixr/docker-zsh-completion
antigen bundle git
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen apply

unalias g

for plugin in $ZSH/plugins/*; do
  source $plugin
done

compdef -d mcd

# Save history
setopt SHARE_HISTORY
# but never repeat same commando twice
setopt HIST_IGNORE_ALL_DUPS

# Save 1000 entries
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.history

# Use Emacs keybindings
bindkey -e

# Use up/down for searching back in history
bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
